#!/bin/bash

python -m venv env
source env/bin/activate
pip install git+https://github.com/lukhen/lukh-fractions.git
python -c "
from lukh_fractions import Fraction
assert Fraction(0).plus(Fraction(0)) == 0"
pip uninstall -y Fractions-module
deactivate
rm -r env

